version: '3'

services:
  locust:
    image: locustio/locust:2.4.3
    environment:
      LOCUST_HOST: http://locust
      LOCUST_MODE_MASTER: "true"
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
    ports:
      - 8089:8089

  worker:
    build:
      context: ..
      dockerfile: example/Dockerfile
    env_file:
      - ./.env
    deploy:
      replicas: 5
    depends_on:
      - locust
